export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_FULFILLED = 'FETCH_NOTIFICATIONS_FULFILLED';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const UPDATE_NOTIFICATIONS_FULFILLED = 'UPDATE_NOTIFICATIONS_FULFILLED';

export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_WITH_NOTE = 'LOGOUT_WITH_NOTE';

export const GROUPS_FETCH = 'GROUPS_FETCH';
export const GROUPS_FETCH_FULFILLED = 'GROUPS_FETCH_FULFILLED';
export const GROUPS_LIST_FETCH = 'GROUPS_LIST_FETCH';
export const GROUPS_LIST_FETCH_FULFILLED = 'GROUPS_LIST_FETCH_FULFILLED';
export const GROUPS_FETCH_FAILED = 'GROUPS_FETCH_FAILED';

export const SUBUNITS_FETCH = 'SUBUNITS_FETCH';
export const SUBUNITS_FETCH_FULFILLED = 'SUBUNITS_FETCH_FULFILLED';
export const SUBUNITS_LIST_FETCH = 'SUBUNITS_LIST_FETCH';
export const SUBUNITS_LIST_FETCH_FULFILLED = 'SUBUNITS_LIST_FETCH_FULFILLED';
export const SUBUNITS_FETCH_FAILED = 'SUBUNITS_FETCH_FAILED';

export const IDOLS_FETCH = 'IDOLS_FETCH';
export const IDOLS_FETCH_FULFILLED = 'IDOLS_FETCH_FULFILLED';
export const IDOLS_LIST_FETCH = 'IDOLS_LIST_FETCH';
export const IDOLS_LIST_FETCH_FULFILLED = 'IDOLS_LIST_FETCH_FULFILLED';
export const IDOLS_FETCH_FAILED = 'IDOLS_FETCH_FAILED';

export const SURVEYS_FETCH = 'SURVEYS_FETCH';
export const SURVEYS_FETCH_FULFILLED = 'SURVEYS_FETCH_FULFILLED';
export const SURVEYS_FETCH_FAILED = 'SURVEYS_FETCH_FAILED';

export const RESPONSES_FETCH = 'RESPONSES_FETCH';
export const RESPONSES_FETCH_FULFILLED = 'RESPONSES_FETCH_FULFILLED';
export const RESPONSES_FETCH_FAILED = 'RESPONSES_FETCH_FAILED';

export const RESPONSES_BYCARD_FETCH = 'RESPONSES_BYCARD_FETCH';
export const RESPONSES_BYCARD_FETCH_FULFILLED = 'RESPONSES_BYCARD_FETCH_FULFILLED';
export const RESPONSES_BYCARD_FETCH_FAILED = 'RESPONSES_BYCARD_FETCH_FAILED';

export const CARDS_FETCH = 'CARDS_FETCH';
export const CARDS_FETCH_FULFILLED = 'CARDS_FETCH_FULFILLED';

export const CARD_FETCH = 'CARD_FETCH';
export const CARD_FETCH_FULFILLED = 'CARD_FETCH_FULFILLED';