export const SURVEY_FETCH = 'SURVEY_FETCH';
export const SURVEY_FETCH_FULFILLED = 'SURVEY_FETCH_FULFILLED';

export const EDIT_SURVEY_START = 'EDIT_SURVEY_START';
export const EDIT_SURVEY_END = 'EDIT_SURVEY_END';

export const NEW_SET_NAME = 'NEW_SET_NAME';
export const NEW_SET_TITLE = 'NEW_SET_TITLE';
export const NEW_SET_COMMENTS = 'NEW_SET_COMMENTS';
export const NEW_SET_SLUG = 'NEW_SET_SLUG';
export const NEW_SET_ACTIVE = 'NEW_SET_ACTIVE';
export const NEW_SET_QUESTIONS = 'NEW_SET_QUESTIONS';

export const NEW_SET_CARD_FILTER = 'NEW_SET_CARD_FILTER';