export const FETCH_SURVEY = 'FETCH_SURVEY';
export const FETCH_SURVEY_FULFILLED = 'FETCH_SURVEY_FULFILLED';

export const SET_CHOICE = 'SET_CHOICE';
export const SET_CARD = 'SET_CARD';
export const SET_SELECTION = 'SET_SELECTION';

export const DISPLAY_CARD = 'DISPLAY_CARD';

export const SUBMIT_SURVEY = 'SUBMIT_SURVEY';
export const SUBMIT_SURVEY_FULFILLED = 'SUBMIT_SURVEY_FULFILLED';

export const SET_SURVEY_ERROR = 'SET_SURVEY_ERROR';
export const CLEAR_SURVEY_ERROR = 'CLEAR_SURVEY_ERROR';

export const FETCH_AKI_PAGE = 'FETCH_AKI_PAGE';
export const FETCH_AKI_PAGE_FULFILLED = 'FETCH_AKI_PAGE_FULFILLED';
